# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_OTPake', [dirname(__file__)])
        except ImportError:
            import _OTPake
            return _OTPake
        if fp is not None:
            try:
                _mod = imp.load_module('_OTPake', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _OTPake = swig_import_helper()
    del swig_import_helper
else:
    import _OTPake
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _OTPake.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _OTPake.SwigPyIterator_value(self)
    def incr(self, n=1): return _OTPake.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _OTPake.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _OTPake.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _OTPake.SwigPyIterator_equal(self, *args)
    def copy(self): return _OTPake.SwigPyIterator_copy(self)
    def next(self): return _OTPake.SwigPyIterator_next(self)
    def __next__(self): return _OTPake.SwigPyIterator___next__(self)
    def previous(self): return _OTPake.SwigPyIterator_previous(self)
    def advance(self, *args): return _OTPake.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _OTPake.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _OTPake.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _OTPake.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _OTPake.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _OTPake.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _OTPake.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _OTPake.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class OTPake(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OTPake, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OTPake, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _OTPake.new_OTPake(*args)
        try: self.this.append(this)
        except: self.this = this
    def getPrime(self): return _OTPake.OTPake_getPrime(self)
    def getGenerator(self): return _OTPake.OTPake_getGenerator(self)
    def getPrivateKey(self): return _OTPake.OTPake_getPrivateKey(self)
    def getSelfEphemeral(self): return _OTPake.OTPake_getSelfEphemeral(self)
    def getOtherEphemeral(self): return _OTPake.OTPake_getOtherEphemeral(self)
    def getSharedSecret(self): return _OTPake.OTPake_getSharedSecret(self)
    def getOTP(self): return _OTPake.OTPake_getOTP(self)
    def getSharedKey(self): return _OTPake.OTPake_getSharedKey(self)
    def getUniqueID(self): return _OTPake.OTPake_getUniqueID(self)
    __swig_destroy__ = _OTPake.delete_OTPake
    __del__ = lambda self : None;
OTPake_swigregister = _OTPake.OTPake_swigregister
OTPake_swigregister(OTPake)

class OTPakeClient(OTPake):
    __swig_setmethods__ = {}
    for _s in [OTPake]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, OTPakeClient, name, value)
    __swig_getmethods__ = {}
    for _s in [OTPake]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, OTPakeClient, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _OTPake.new_OTPakeClient(*args)
        try: self.this.append(this)
        except: self.this = this
    def genSharedKey(self, *args): return _OTPake.OTPakeClient_genSharedKey(self, *args)
    def getVerification(self): return _OTPake.OTPakeClient_getVerification(self)
    __swig_destroy__ = _OTPake.delete_OTPakeClient
    __del__ = lambda self : None;
OTPakeClient_swigregister = _OTPake.OTPakeClient_swigregister
OTPakeClient_swigregister(OTPakeClient)

class OTPakeServer(OTPake):
    __swig_setmethods__ = {}
    for _s in [OTPake]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, OTPakeServer, name, value)
    __swig_getmethods__ = {}
    for _s in [OTPake]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, OTPakeServer, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _OTPake.new_OTPakeServer(*args)
        try: self.this.append(this)
        except: self.this = this
    def genSharedKey(self, *args): return _OTPake.OTPakeServer_genSharedKey(self, *args)
    def getVerifications(self): return _OTPake.OTPakeServer_getVerifications(self)
    def getOTPs(self): return _OTPake.OTPakeServer_getOTPs(self)
    def getSharedSecrets(self): return _OTPake.OTPakeServer_getSharedSecrets(self)
    def __reduce__(self):
       return (self.__class__,(
            self.getPrivateKey(),
            self.getSelfEphemeral(),
            self.getOtherEphemeral(),
            self.getUniqueID(),
            self.getVerifications(),
            self.getOTPs(),
            self.getSharedSecrets()
       ))

    __swig_destroy__ = _OTPake.delete_OTPakeServer
    __del__ = lambda self : None;
OTPakeServer_swigregister = _OTPake.OTPakeServer_swigregister
OTPakeServer_swigregister(OTPakeServer)

# This file is compatible with both classic and new-style classes.


